/******************************************************************************
 * AUTO-GENERATED FILE — DO NOT EDIT
 *
 * Generated by: python -m ramulator codegen
 * Source:       python/ramulator/dram/ddr4_pud.py
 *
 * Regenerate:   python -m ramulator codegen DDR4_PuD
 ******************************************************************************/
#include "ramulator/dram/commands/ACT.h"
#include "ramulator/dram/commands/ACT_PUD.h"
#include "ramulator/dram/commands/ACT_PUD_OC.h"
#include "ramulator/dram/commands/ACT_PUD_S.h"
#include "ramulator/dram/commands/ACT_PUD_S_OC.h"
#include "ramulator/dram/commands/N.h"
#include "ramulator/dram/commands/PREab.h"
#include "ramulator/dram/commands/PREpb.h"
#include "ramulator/dram/commands/RD.h"
#include "ramulator/dram/commands/RDA.h"
#include "ramulator/dram/commands/REFab.h"
#include "ramulator/dram/commands/WR.h"
#include "ramulator/dram/commands/WRA.h"
#include "ramulator/dram/commands/populate.h"
#include "ramulator/dram/dram_spec.h"

namespace Ramulator {

class DDR4_PuD : public DRAMSpec {
 public:
  struct Level {
    enum : int { Channel, Rank, BankGroup, Bank, Row, Column, COUNT };
  };
  struct Command {
    enum : int { ACT, PREpb, PREab, RD, WR, RDA, WRA, REFab, ACT_PUD, ACT_PUD_OC, ACT_PUD_S, ACT_PUD_S_OC, N, COUNT };
  };
  struct State {
    enum : int { Opened, Closed, N_A, PuDChargeSharing, PuDSensed, COUNT };
  };
  struct Timing {
    enum : int {
      rate,
      nBL,
      nCL,
      nRCD,
      nRP,
      nRAS,
      nRC,
      nWR,
      nRTP,
      nCWL,
      nCCDS,
      nCCDL,
      nRRDS,
      nRRDL,
      nWTRS,
      nWTRL,
      nFAW,
      nRFC,
      nREFI,
      nCS,
      tCK_ps,
      nPUD_ACT_OC,
      nPUD_ACT,
      nPUD_ACT_S_OC,
      nPUD_ACT_S,
      nPUD_N,
      COUNT
    };
  };

  using CommandImpls =
      std::tuple<Cmd::ACT<DDR4_PuD>, Cmd::PREpb<DDR4_PuD>, Cmd::PREab<DDR4_PuD>, Cmd::RD<DDR4_PuD>, Cmd::WR<DDR4_PuD>,
                 Cmd::RDA<DDR4_PuD>, Cmd::WRA<DDR4_PuD>, Cmd::REFab<DDR4_PuD>, Cmd::ACT_PUD<DDR4_PuD>,
                 Cmd::ACT_PUD_OC<DDR4_PuD>, Cmd::ACT_PUD_S<DDR4_PuD>, Cmd::ACT_PUD_S_OC<DDR4_PuD>, Cmd::N<DDR4_PuD> >;

  DDR4_PuD(const ConfigNode& config) {
    // Counts
    level_count = Level::COUNT;
    command_count = Command::COUNT;
    state_count = State::COUNT;
    timing_count = Timing::COUNT;

    // String name maps + reverse lookup vectors
    set_names(levels, level_names, {"Channel", "Rank", "BankGroup", "Bank", "Row", "Column"});
    set_names(commands, command_names,
              {"ACT", "PREpb", "PREab", "RD", "WR", "RDA", "WRA", "REFab", "ACT_PUD", "ACT_PUD_OC", "ACT_PUD_S",
               "ACT_PUD_S_OC", "N"});
    set_names(states, state_names, {"Opened", "Closed", "N_A", "PuDChargeSharing", "PuDSensed"});
    set_names(timings, timing_names,
              {"rate",  "nBL",   "nCL",    "nRCD",        "nRP",      "nRAS",          "nRC",        "nWR",   "nRTP",
               "nCWL",  "nCCDS", "nCCDL",  "nRRDS",       "nRRDL",    "nWTRS",         "nWTRL",      "nFAW",  "nRFC",
               "nREFI", "nCS",   "tCK_ps", "nPUD_ACT_OC", "nPUD_ACT", "nPUD_ACT_S_OC", "nPUD_ACT_S", "nPUD_N"});

    // Static spec data
    internal_prefetch_size = 8;
    init_states = {
        State::N_A,     // Channel
        State::N_A,     // Rank
        State::N_A,     // BankGroup
        State::Closed,  // Bank
        State::Closed,  // Row
        State::N_A,     // Column
    };
    supported_requests = {
        Command::RD,                     // Read -> RD
        Command::WR,                     // Write -> WR
        DRAMSpec::CONTROLLER_SEQUENCED,  // RowCopy -> controller sequence
        DRAMSpec::CONTROLLER_SEQUENCED,  // MAJ3 -> controller sequence
        DRAMSpec::CONTROLLER_SEQUENCED,  // MAJ5 -> controller sequence
        DRAMSpec::CONTROLLER_SEQUENCED,  // NOT -> controller sequence
    };

    // Runtime config (organization, timing values, timing constraints)
    load_config(config);

    // Command handlers (function pointers, metadata, bank targets)
    populate_commands(CommandImpls{}, *this);
  }
};

// Self-registration
static bool _dram_ddr4_pud = DRAMSpec::register_standard(
    "DDR4_PuD", [](const ConfigNode& config) { return std::make_unique<DDR4_PuD>(config); });

}  // namespace Ramulator
