/******************************************************************************
 * AUTO-GENERATED FILE — DO NOT EDIT
 *
 * Generated by: python -m ramulator codegen
 * Source:       python/ramulator/dram/ddr4_pud_movement.py
 *
 * Regenerate:   python -m ramulator codegen DDR4_PuD_Movement
 ******************************************************************************/
#include "ramulator/dram/commands/ACT.h"
#include "ramulator/dram/commands/ACT_MOV.h"
#include "ramulator/dram/commands/ACT_PUD.h"
#include "ramulator/dram/commands/ACT_PUD_OC.h"
#include "ramulator/dram/commands/ACT_PUD_S.h"
#include "ramulator/dram/commands/ACT_PUD_S_OC.h"
#include "ramulator/dram/commands/N.h"
#include "ramulator/dram/commands/PREab.h"
#include "ramulator/dram/commands/PREpb.h"
#include "ramulator/dram/commands/RD.h"
#include "ramulator/dram/commands/RDA.h"
#include "ramulator/dram/commands/RD_MOV.h"
#include "ramulator/dram/commands/REFab.h"
#include "ramulator/dram/commands/WR.h"
#include "ramulator/dram/commands/WRA.h"
#include "ramulator/dram/commands/WR_MOV.h"
#include "ramulator/dram/commands/populate.h"
#include "ramulator/dram/dram_spec.h"

namespace Ramulator {

class DDR4_PuD_Movement : public DRAMSpec {
 public:
  struct Level {
    enum : int { Channel, Rank, BankGroup, Bank, Row, Column, COUNT };
  };
  struct Command {
    enum : int {
      ACT,
      PREpb,
      PREab,
      RD,
      WR,
      RDA,
      WRA,
      REFab,
      ACT_PUD,
      ACT_PUD_OC,
      ACT_PUD_S,
      ACT_PUD_S_OC,
      N,
      ACT_MOV,
      RD_MOV,
      WR_MOV,
      COUNT
    };
  };
  struct State {
    enum : int { Opened, Closed, N_A, PuDChargeSharing, PuDSensed, MovementActive, MovementDataValid, COUNT };
  };
  struct Timing {
    enum : int {
      rate,
      nBL,
      nCL,
      nRCD,
      nRP,
      nRAS,
      nRC,
      nWR,
      nRTP,
      nCWL,
      nCCDS,
      nCCDL,
      nRRDS,
      nRRDL,
      nWTRS,
      nWTRL,
      nFAW,
      nRFC,
      nREFI,
      nCS,
      tCK_ps,
      nPUD_ACT_OC,
      nPUD_ACT,
      nPUD_ACT_S_OC,
      nPUD_ACT_S,
      nPUD_N,
      nRELOC,
      COUNT
    };
  };

  using CommandImpls =
      std::tuple<Cmd::ACT<DDR4_PuD_Movement>, Cmd::PREpb<DDR4_PuD_Movement>, Cmd::PREab<DDR4_PuD_Movement>,
                 Cmd::RD<DDR4_PuD_Movement>, Cmd::WR<DDR4_PuD_Movement>, Cmd::RDA<DDR4_PuD_Movement>,
                 Cmd::WRA<DDR4_PuD_Movement>, Cmd::REFab<DDR4_PuD_Movement>, Cmd::ACT_PUD<DDR4_PuD_Movement>,
                 Cmd::ACT_PUD_OC<DDR4_PuD_Movement>, Cmd::ACT_PUD_S<DDR4_PuD_Movement>,
                 Cmd::ACT_PUD_S_OC<DDR4_PuD_Movement>, Cmd::N<DDR4_PuD_Movement>, Cmd::ACT_MOV<DDR4_PuD_Movement>,
                 Cmd::RD_MOV<DDR4_PuD_Movement>, Cmd::WR_MOV<DDR4_PuD_Movement> >;

  DDR4_PuD_Movement(const ConfigNode& config) {
    // Counts
    level_count = Level::COUNT;
    command_count = Command::COUNT;
    state_count = State::COUNT;
    timing_count = Timing::COUNT;

    // String name maps + reverse lookup vectors
    set_names(levels, level_names, {"Channel", "Rank", "BankGroup", "Bank", "Row", "Column"});
    set_names(commands, command_names,
              {"ACT", "PREpb", "PREab", "RD", "WR", "RDA", "WRA", "REFab", "ACT_PUD", "ACT_PUD_OC", "ACT_PUD_S",
               "ACT_PUD_S_OC", "N", "ACT_MOV", "RD_MOV", "WR_MOV"});
    set_names(states, state_names,
              {"Opened", "Closed", "N_A", "PuDChargeSharing", "PuDSensed", "MovementActive", "MovementDataValid"});
    set_names(
        timings, timing_names,
        {"rate",  "nBL",   "nCL",    "nRCD",        "nRP",      "nRAS",          "nRC",        "nWR",    "nRTP",
         "nCWL",  "nCCDS", "nCCDL",  "nRRDS",       "nRRDL",    "nWTRS",         "nWTRL",      "nFAW",   "nRFC",
         "nREFI", "nCS",   "tCK_ps", "nPUD_ACT_OC", "nPUD_ACT", "nPUD_ACT_S_OC", "nPUD_ACT_S", "nPUD_N", "nRELOC"});

    // Static spec data
    internal_prefetch_size = 8;
    supports_hffs_per_mat = true;
    init_states = {
        State::N_A,     // Channel
        State::N_A,     // Rank
        State::N_A,     // BankGroup
        State::Closed,  // Bank
        State::Closed,  // Row
        State::N_A,     // Column
    };
    supported_requests = {
        Command::RD,                     // Read -> RD
        Command::WR,                     // Write -> WR
        DRAMSpec::CONTROLLER_SEQUENCED,  // RowCopy -> controller sequence
        DRAMSpec::CONTROLLER_SEQUENCED,  // MAJ3 -> controller sequence
        DRAMSpec::CONTROLLER_SEQUENCED,  // MAJ5 -> controller sequence
        DRAMSpec::CONTROLLER_SEQUENCED,  // NOT -> controller sequence
    };

    // Runtime config (organization, timing values, timing constraints)
    load_config(config);

    // Command handlers (function pointers, metadata, bank targets)
    populate_commands(CommandImpls{}, *this);
  }
};

// Self-registration
static bool _dram_ddr4_pud_movement = DRAMSpec::register_standard(
    "DDR4_PuD_Movement", [](const ConfigNode& config) { return std::make_unique<DDR4_PuD_Movement>(config); });

}  // namespace Ramulator
