/******************************************************************************
 * AUTO-GENERATED FILE — DO NOT EDIT
 *
 * Generated by: python -m ramulator codegen
 * Source:       python/ramulator/dram/hbm3_pud.py
 *
 * Regenerate:   python -m ramulator codegen HBM3_PuD
 ******************************************************************************/
#include "ramulator/dram/commands/ACT.h"
#include "ramulator/dram/commands/ACT_MOV.h"
#include "ramulator/dram/commands/ACT_PUD.h"
#include "ramulator/dram/commands/ACT_PUD_OC.h"
#include "ramulator/dram/commands/ACT_PUD_S.h"
#include "ramulator/dram/commands/ACT_PUD_S_OC.h"
#include "ramulator/dram/commands/N.h"
#include "ramulator/dram/commands/PREab.h"
#include "ramulator/dram/commands/PREpb.h"
#include "ramulator/dram/commands/RD.h"
#include "ramulator/dram/commands/RDA.h"
#include "ramulator/dram/commands/RD_MOV.h"
#include "ramulator/dram/commands/REFab.h"
#include "ramulator/dram/commands/REFpb.h"
#include "ramulator/dram/commands/RFMab.h"
#include "ramulator/dram/commands/RFMpb.h"
#include "ramulator/dram/commands/WR.h"
#include "ramulator/dram/commands/WRA.h"
#include "ramulator/dram/commands/WR_MOV.h"
#include "ramulator/dram/commands/populate.h"
#include "ramulator/dram/dram_spec.h"

namespace Ramulator {

class HBM3_PuD : public DRAMSpec {
 public:
  struct Level {
    enum : int { Channel, PseudoChannel, Sid, BankGroup, Bank, Row, Column, COUNT };
  };
  struct Command {
    enum : int {
      ACT,
      PREpb,
      PREab,
      RD,
      WR,
      RDA,
      WRA,
      REFab,
      REFpb,
      RFMab,
      RFMpb,
      ACT_PUD,
      ACT_PUD_OC,
      ACT_PUD_S,
      ACT_PUD_S_OC,
      N,
      ACT_MOV,
      RD_MOV,
      WR_MOV,
      COUNT
    };
  };
  struct State {
    enum : int { Opened, Closed, N_A, PuDChargeSharing, PuDSensed, MovementActive, MovementDataValid, COUNT };
  };
  struct Timing {
    enum : int {
      rate,
      nBL,
      nCL,
      nRCDRD,
      nRCDWR,
      nRP,
      nRAS,
      nRC,
      nWR,
      nRTP,
      nCWL,
      nCCDS,
      nCCDL,
      nCCDR,
      nRRDS,
      nRRDL,
      nWTRS,
      nWTRL,
      nRTW,
      nFAW,
      nPPD,
      nRFC,
      nRFCpb,
      nRFMab,
      nRFMpb,
      nRREFD,
      nREFI,
      nREFIpb,
      tCK_ps,
      nPUD_ACT_OC,
      nPUD_ACT,
      nPUD_ACT_S_OC,
      nPUD_ACT_S,
      nPUD_N,
      nRELOC,
      COUNT
    };
  };

  using CommandImpls =
      std::tuple<Cmd::ACT<HBM3_PuD>, Cmd::PREpb<HBM3_PuD>, Cmd::PREab<HBM3_PuD>, Cmd::RD<HBM3_PuD>, Cmd::WR<HBM3_PuD>,
                 Cmd::RDA<HBM3_PuD>, Cmd::WRA<HBM3_PuD>, Cmd::REFab<HBM3_PuD>, Cmd::REFpb<HBM3_PuD>,
                 Cmd::RFMab<HBM3_PuD>, Cmd::RFMpb<HBM3_PuD>, Cmd::ACT_PUD<HBM3_PuD>, Cmd::ACT_PUD_OC<HBM3_PuD>,
                 Cmd::ACT_PUD_S<HBM3_PuD>, Cmd::ACT_PUD_S_OC<HBM3_PuD>, Cmd::N<HBM3_PuD>, Cmd::ACT_MOV<HBM3_PuD>,
                 Cmd::RD_MOV<HBM3_PuD>, Cmd::WR_MOV<HBM3_PuD> >;

  HBM3_PuD(const ConfigNode& config) {
    // Counts
    level_count = Level::COUNT;
    command_count = Command::COUNT;
    state_count = State::COUNT;
    timing_count = Timing::COUNT;

    // String name maps + reverse lookup vectors
    set_names(levels, level_names, {"Channel", "PseudoChannel", "Sid", "BankGroup", "Bank", "Row", "Column"});
    set_names(commands, command_names,
              {"ACT", "PREpb", "PREab", "RD", "WR", "RDA", "WRA", "REFab", "REFpb", "RFMab", "RFMpb", "ACT_PUD",
               "ACT_PUD_OC", "ACT_PUD_S", "ACT_PUD_S_OC", "N", "ACT_MOV", "RD_MOV", "WR_MOV"});
    set_names(states, state_names,
              {"Opened", "Closed", "N_A", "PuDChargeSharing", "PuDSensed", "MovementActive", "MovementDataValid"});
    set_names(
        timings, timing_names,
        {"rate",    "nBL",    "nCL",         "nRCDRD",   "nRCDWR",        "nRP",        "nRAS",   "nRC",    "nWR",
         "nRTP",    "nCWL",   "nCCDS",       "nCCDL",    "nCCDR",         "nRRDS",      "nRRDL",  "nWTRS",  "nWTRL",
         "nRTW",    "nFAW",   "nPPD",        "nRFC",     "nRFCpb",        "nRFMab",     "nRFMpb", "nRREFD", "nREFI",
         "nREFIpb", "tCK_ps", "nPUD_ACT_OC", "nPUD_ACT", "nPUD_ACT_S_OC", "nPUD_ACT_S", "nPUD_N", "nRELOC"});

    // Static spec data
    internal_prefetch_size = 8;
    supports_hffs_per_mat = true;
    init_states = {
        State::N_A,     // Channel
        State::N_A,     // PseudoChannel
        State::N_A,     // Sid
        State::N_A,     // BankGroup
        State::Closed,  // Bank
        State::Closed,  // Row
        State::N_A,     // Column
    };
    supported_requests = {
        Command::RD,                     // Read -> RD
        Command::WR,                     // Write -> WR
        DRAMSpec::CONTROLLER_SEQUENCED,  // RowCopy -> controller sequence
        DRAMSpec::CONTROLLER_SEQUENCED,  // MAJ3 -> controller sequence
        DRAMSpec::CONTROLLER_SEQUENCED,  // MAJ5 -> controller sequence
        DRAMSpec::CONTROLLER_SEQUENCED,  // NOT -> controller sequence
        DRAMSpec::CONTROLLER_SEQUENCED,  // NOT_COPY -> controller sequence
        DRAMSpec::CONTROLLER_SEQUENCED,  // LC-MOV -> controller sequence
        DRAMSpec::CONTROLLER_SEQUENCED,  // GB-MOV -> controller sequence
    };

    // Runtime config (organization, timing values, timing constraints)
    load_config(config);

    // Command handlers (function pointers, metadata, bank targets)
    populate_commands(CommandImpls{}, *this);

    // Bus classification (for dual-bus controllers)
    command_meta[Command::ACT].is_row_command = true;
    command_meta[Command::PREpb].is_row_command = true;
    command_meta[Command::PREab].is_row_command = true;
    command_meta[Command::REFab].is_row_command = true;
    command_meta[Command::REFpb].is_row_command = true;
    command_meta[Command::RFMab].is_row_command = true;
    command_meta[Command::RFMpb].is_row_command = true;
    command_meta[Command::ACT_PUD].is_row_command = true;
    command_meta[Command::ACT_PUD_OC].is_row_command = true;
    command_meta[Command::ACT_PUD_S].is_row_command = true;
    command_meta[Command::ACT_PUD_S_OC].is_row_command = true;
    command_meta[Command::N].is_row_command = true;
    command_meta[Command::ACT_MOV].is_row_command = true;
    command_meta[Command::RD].is_column_command = true;
    command_meta[Command::WR].is_column_command = true;
    command_meta[Command::RDA].is_column_command = true;
    command_meta[Command::WRA].is_column_command = true;
    command_meta[Command::RD_MOV].is_column_command = true;
    command_meta[Command::WR_MOV].is_column_command = true;
  }
};

// Self-registration
static bool _dram_hbm3_pud = DRAMSpec::register_standard(
    "HBM3_PuD", [](const ConfigNode& config) { return std::make_unique<HBM3_PuD>(config); });

}  // namespace Ramulator
