"""Authoritative physical requirements for the six GEMV arithmetic profiles."""
import argparse
import json
from pathlib import Path

from .fp8 import build_e4m3_add, build_e4m3_mul, build_e5m2_add, build_e5m2_mul
from .integer import build_int8_add, build_int8_mul
from .lowering import lower_to_physical, make_default_physical_layout

BUILDERS = {
    "int8-add": build_int8_add, "int8-mul": build_int8_mul,
    "fp8-e4m3-add": build_e4m3_add, "fp8-e4m3-mul": build_e4m3_mul,
    "fp8-e5m2-add": build_e5m2_add, "fp8-e5m2-mul": build_e5m2_mul,
}


def operation_requirements():
    """Derive counts from the actual lowered programs, without arithmetic replay."""
    profiles = {}
    for name, factory in BUILDERS.items():
        program = factory()
        lowered = lower_to_physical(program, make_default_physical_layout(program))
        profiles[name] = {
            "profile": name,
            "input_rows": len(lowered.designated_inputs),
            "output_rows": len(lowered.designated_outputs),
            "constant_rows": len(lowered.designated_constants),
            "additional_temporary_rows": lowered.additional_temporary_rows,
            "primitive_count": len(lowered.primitives),
        }
    return profiles


def write_requirements(directory):
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    profiles = operation_requirements()
    document = {"schema_version": 1, "profiles": profiles}
    (directory / "pud_operation_requirements.json").write_text(
        json.dumps(document, indent=2) + "\n", encoding="utf-8"
    )
    lines = [
        "/* Generated by tools.pud_operation_generator.requirements; do not edit. */",
        "#ifndef PUD_OPERATION_REQUIREMENTS_H",
        "#define PUD_OPERATION_REQUIREMENTS_H",
        "",
    ]
    names = {
        "input_rows": "INPUT_ROWS", "output_rows": "OUTPUT_ROWS",
        "constant_rows": "CONSTANT_ROWS", "additional_temporary_rows": "TMP_ROWS",
        "primitive_count": "PRIMITIVE_COUNT",
    }
    for profile, record in profiles.items():
        for field, suffix in names.items():
            lines.append(f"#define PUD_{profile.upper().replace('-', '_')}_{suffix} {record[field]}")
    lines += ["", "#endif", ""]
    (directory / "pud_operation_requirements.h").write_text("\n".join(lines), encoding="utf-8")
    return document


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=Path("build/pud-gemv/generated"))
    write_requirements(parser.parse_args().out)
