###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/frontend/impl/memory_trace/pud_trace.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class PuDTrace(Component):
    impl = "PuDTrace"
    clock_ratio = Param(int, required=True, cpp_type="unsigned int")
    path = Param(str, required=True)
    latency_chain_ids = Param(list, default=[], cpp_type="std::vector<int>")
    latency_checkpoint_requests = Param(list, default=[], cpp_type="std::vector<int>")
